command:
  - "python"
  - "app.py"

env:
  - name: LAKEBASE_SECRET_SCOPE
    value: "database"
  - name: LAKEBASE_SECRET_KEY
    value: "lakebase-url"
  - name: MASSIVE_API_BASE_URL
    value: "https://api.polygon.io/"
  - name: MASSIVE_SECRET_SCOPE
    value: "massive"
  - name: MASSIVE_SECRET_KEY
    value: "api-key"
